set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/")

find_package(SDL2 REQUIRED)
find_package(SDL2-image REQUIRED)
set(PLATFORM_LIBRARIES
	SDL2::SDL2
	SDL2::SDL2_image
	${CMAKE_DL_LIBS}
)
set(PLATFORM_INCLUDE_DIRS
	${CMAKE_CURRENT_BINARY_DIR}
	${SRC}
	${SRC}/Platform/${PLATFORM_NAME}/PlatformSupport
	${SDL2_INCLUDE_DIRS}
)

include(${SRC}/Platform/Util/AddBinary.cmake)

AddBinary(
	PlatformSDL2
	LIBRARY
	SOURCES ${PLATFORM_SOURCES} ${PLATFORM_HEADERS}
	INCLUDE_DIRS ${PLATFORM_INCLUDE_DIRS}
	LIBRARIES ${PLATFORM_LIBRARIES}
)

AddBinary(
	Client
	EXECUTABLE
	SOURCES "Game.cpp" ${PLATFORM_HEADERS}
	INCLUDE_DIRS ${PLATFORM_INCLUDE_DIRS}
	LIBRARIES
		SDL2::SDL2main
		PlatformSDL2
		${PLATFORM_LIBRARIES}
)
