set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/")

find_package(SDL2 REQUIRED)
find_package(SDL2-image REQUIRED)

set(PLATFORM_LIBRARIES
	SDL2::SDL2
	SDL2::SDL2_image
	${CMAKE_DL_LIBS}
)

set(PLATFORM_INCLUDE_DIRS
	${CMAKE_CURRENT_BINARY_DIR}
	${SRC}
	${SDL2_INCLUDE_DIRS}
	${PLATFORM_HEADERS}
)

include(${SRC}/Platform/Util/AddBinary.cmake)

#AddBinary(
#	PlatformSDL2
#	LIBRARY
#	SOURCES ${PLATFORM_SOURCES} ${PLATFORM_HEADERS}
#	INCLUDE_DIRS ${PLATFORM_INCLUDE_DIRS}
#	LIBRARIES ${PLATFORM_LIBRARIES}
#)

project(Client)
AddBinary(
	Client
	EXECUTABLE
	SOURCES ${PLATFORM_HEADERS} ${PLATFORM_SOURCES}
	INCLUDE_DIRS ${PLATFORM_INCLUDE_DIRS}
	LIBRARIES
		Registry
		SDL2::SDL2main
		${PLATFORM_LIBRARIES}
)

set_target_properties( 
		Client
     PROPERTIES
		ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/archive"
		LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin/plugins"
		RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin"
		PDB_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/pdb"
)